### ISSUE TITLE
Foodcritic does not seem to run

### ISSUE THREAD

**Issue by scarolan** [pendrica/vscode-chef#11] opened 2016-06-17 22:07 UTC
I added some things that should have caused foodcritic violations to my recipe.

**Comment by stuartpreston** [comment] 2016-06-18 02:52
Hi @scarolan - we're going to need a bit more info in order to diagnose the issue. The following list comes to mind:

- How did you enable Foodcritic support? User settings or workspace settings?  Did you reload VSCode?
- Is your top level folder you selected a cookbook or a chef repo?
- What version of ChefDK are you running?  Can you provide the path to Foodcritic bin stub on your system.
- What version of VSCode are you running?
- What platform are you running on?
- If you enable the developer tools are there any messages in the console when you reload the folder and open your recipe?

**Comment by ruicovelo** [comment] 2016-10-20 07:20
I am having the same problem since recently. Was working the first time I installed the extension. Troubleshooting the problem I came across default settings. It defaults to false (this changed right?) so I set a User setting to true.

My top level folder is the cookbooks folder.
ChefDK v0.12.0
/c/opscode/chefdk/bin/foodcritic
VSCode 1.6.1
Windows 10

Developer tools console 

> [Extension Host] SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at validateWorkspace (C:\Users\ruc\.vscode\extensions\Pendrica.Chef-0.6.1\out\extension.js:86:34)
    at activate (C:\Users\ruc\.vscode\extensions\Pendrica.Chef-0.6.1\out\extension.js:28:9)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:15169)
    at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:14952)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:14824
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5002)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:8580)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10408)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9849)
threadService.ts:222 [Extension Host] bootos
threadService.ts:222 [Extension Host] chef_handler
(... all my other cookbooks here ...)
threadService.ts:222 [Extension Host] in validate cookbooks
threadService.ts:222 [Extension Host] Foodcritic executed but exited with status: 1

**Comment by ruicovelo** [comment] 2016-10-20 07:45
Update ChefDK to 0.18.30 (rubocop 0.39.0 - was 0.37.2). Still same error.

I opened the json generated by rubocop with atom and atom does not seem to be able to parse it either.

**Comment by stuartpreston** [comment] 2016-10-31 21:53
@ruicovelo Did you mean foodcritic in place of rubocop here?

**Comment by zivagolee** [comment] 2017-04-11 18:54
I am seeing the same thing on MacOS 10.12.4. I have ChefDK 1.3.40 installed but I don't see foodcritic running at all. VSCode is at 1.11.1

Any suggestions on how to debug?

**Comment by ruicovelo** [comment] 2017-04-12 11:15
Sorry for taking so much time to get back but the thing is I am no longer able to reproduce the issue in any of my machines :/

**Comment by stuartpreston** [comment] 2017-06-06 21:48
Closing due to age > 1 year

**Closed by stuartpreston** 2017-06-06 21:48 UTC
